# Generated by Django 5.0.1 on 2024-04-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(blank=True, max_length=36, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("rate", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_group", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.nomenclature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.menu"
                    ),
                ),
                (
                    "nomenclature",
                    models.ManyToManyField(
                        related_name="menucontent_nomenclature", to="food.nomenclature"
                    ),
                ),
            ],
        ),
    ]
