# Generated by Django 5.0.1 on 2024-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomenclature",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="rate",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
