# Generated by Django 5.0.1 on 2024-02-06 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_alter_nomenclature_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="content",
        ),
    ]
