# Generated by Django 5.0.1 on 2024-02-06 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_alter_menucontent_unique_together_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="count",
        ),
        migrations.RemoveField(
            model_name="order",
            name="menu_content",
        ),
        migrations.CreateModel(
            name="OrderContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(99),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "menu_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.menucontent",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.order"
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "menu_content")},
            },
        ),
    ]
