# Generated by Django 5.0.1 on 2024-02-29 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordercontent",
            old_name="count",
            new_name="amount",
        ),
    ]
