# Generated by Django 5.0.1 on 2024-04-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="content",
            field=models.ManyToManyField(
                through="orders.OrderContent", to="food.menucontent"
            ),
        ),
        migrations.AlterField(
            model_name="ordercontent",
            name="menu_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.menucontent"
            ),
        ),
    ]
