# Generated by Django 5.0.1 on 2024-04-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
        ("orders", "0002_alter_order_content_alter_ordercontent_menu_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercontent",
            name="menu_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_to_order",
                to="food.menucontent",
            ),
        ),
        migrations.AlterField(
            model_name="ordercontent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_to_menu",
                to="orders.order",
            ),
        ),
    ]
