# Generated by Django 5.0.1 on 2024-04-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
        ("orders", "0003_alter_ordercontent_menu_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="content",
        ),
        migrations.AlterField(
            model_name="ordercontent",
            name="menu_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="food.menucontent",
            ),
        ),
        migrations.AlterField(
            model_name="ordercontent",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="orders.order",
            ),
        ),
    ]
