# Generated by Django 5.0.1 on 2024-04-10 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
        (
            "orders",
            "0004_remove_order_content_alter_ordercontent_menu_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="menu",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="food.menu"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordercontent",
            name="amount",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(10),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
